. .\homaas_v2\Add-NetworkLocation_for_LinkFixer.ps1

Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\bhgdata\IT"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\grpdata\cb2-data"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\AASSISTANTS"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\ACCOUNTS"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\Commercial"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\Company Policies"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\:\BHGDATA\Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\CSERVICE"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\DFS"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\HEXECS"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\HRESOURCES"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\MARKETING"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\MRESEARCH"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\PARTNERSHIP & KEY ACCOUNTS"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\PURCHASING"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\SALES"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\Temp Data Folder"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\WAREHOUSE"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahbnas01.bs2.heiway.net\BHGDATA\Publication of Policies"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\ACCOUNT"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\APP"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\CommonAll"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\Company Policies"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\DATA"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\Fayrouz sampling @ I.A.A.F. 2015"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\HR"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\Install Folder"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\PM PILLAR TEMPLATE"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\Production"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\San Doc"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\Temp Folder"
Add-HEINEKENNetworkLocation -networkLocation "\\mmosbahcnas01.bs2.heiway.net\GRPDATA\THM"
