. .\Add-NetworkLocation_on_WinServer.ps1

Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\GeneralManagmentDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\LegalDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\ProcurementDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\RevenueManagementDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\LegalDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\ManagementDirectors"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\MarketingDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\KAM_Department"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\OfficeManagementDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\SalesOfftradeDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\SalesOfftradeDepartmentCM"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\SalesOntradeDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\SalesOntradeDepartmentCM"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\SalesSupportDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\KAM_DepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\OfficeManagementDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\SalesDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\SalesOfftradeDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\SalesOntradeDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\SalesSupportDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\FinanceDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\FinanceDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\CustomerServiceDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEDepartments$\LogisticDepartment"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEManager$\LogisticDepartmentManager"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEConfidential$\Beertender"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEConfidential$\BusinessplanCreation"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEConfidential$\Meetings"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDEConfidential$\Praesentationen"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Alex-Sven"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Artikelpässe"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Artikelstammdatenanforderungen"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\ASA"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\AUDIT"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Audit_2018"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Belland Vision"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Blade"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\BR-HR"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Buchhaltung S&N"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Climate Survey Task Force 2016"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Confidential Data Sales"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Contract Management"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Controlling-IT"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Controlling-OnTrade"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Crisis Manual"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\CS_SST_Accounting"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\DataPrivacyTeam"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\DER GRÜNER PUNKT"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\DEV_SEM_MDM"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\eCommerce - Sales"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\EDI"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\EDI Projekte"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Einkauf - General Management"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Einkauf-Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Einkauf-SST"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\ExportSalesVolume2SEM"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Externe Artikelpässe"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\FD-PM"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Finance - OnTrade"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Finance - SST"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Forecast"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Gedat"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Goesser_Marken_Stick_DE_2020"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Green Active"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Greenbook 2.0"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Head of Controlling - Team and Handover"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HEIRules"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HGSS-OpCo"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HR_Reporting"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HR-Accounting"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HR-IT"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HR-OM"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HR-Praktikant"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\HR-Sales"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Information Security"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Inventurrichtlinie"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Issue Management"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\IT-Accounting"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\IT-ChangeManagement"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\IT-Legal"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\IT-Sales"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\IT-SST"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Joiner Leaver Mover Process"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\KAM - Revenue Mgmt"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Kundenakten"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Legal Credit Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Logistik - Sales"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Logistik-Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Logistik-Marketing"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Marketing-Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Marketing-Legal"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Marketing-Sales"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Marktdaten"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Master_Data_Management_HDE"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\MDM Cleansing"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Meeting_2020_Termine"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\MSO"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\MT - Office Management"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\MT - Sales"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\My Green Day"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\NCI"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Nielsen Reports"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\NPI"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\OM-SST"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Paketdienst"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Payroll"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Payroll-Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Personal-Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Pollux"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\POS"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Procurement-Legal"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Project Contract Management"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Projekt SAP Berechtigung"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Projekt Schanktechnik"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Projekt-RADAR"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SALES"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Sales Support und Vertrieb Offtrade"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Sales-Controlling"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SalesOfftradeDepartmentKAMandField"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SEM 3.5"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SEM Power BI"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SEM_MDM"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SNSalesSupport"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SP_Data_Reports"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SST-Accounting"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\SSTOntrade-Legal"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Strategic Analysis"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Uebergabe_Coms"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\UebergabeSarina"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\VMD - Procurement"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\WA - MT"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Warehouse move"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Ways Of Working"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Wirtschaftspruefung"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Zertifikate"
Add-HEINEKENNetworkLocation -networkLocation "\\DE1SFILE01.DE1.HEIWAY.NET\HDECollaboration$\Zuordnungen GFGH"