. .\Add-NetworkLocation_on_WinServer.ps1

Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\BTD Archief\Algemeen" -networklocationname "BTD Archief - Algemeen"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\BTD Archief\Laboratorium"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\BTD Archief\Technologen"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Facilitaire Diensten\SHE (Safety Health Environment)\Environment"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Facilitaire Diensten\SHE (Safety Health Environment)\Health"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Facilitaire Diensten\SHE (Safety Health Environment)\Organisatorisch"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Facilitaire Diensten\SHE (Safety Health Environment)\Quality Assurance"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Facilitaire Diensten\SHE (Safety Health Environment)\Safety"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Facilitaire Diensten\SHE (Safety Health Environment)\TPM"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\Algemeen" -networklocationname "Productie - Algemeen"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\Siroophal"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 1\Colonne 01"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 3\Colonne 03"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 3\Colonne 06"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 3\Colonne 07"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 3\Colonne 09"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 3\Colonne 10"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 4\Colonne 04"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\VruCluster 4\Colonne 05"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Productie\InstallatieBeheer"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Technische Dienst\Algemeen" -networklocationname "Technische Dienst Algemeen"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Technische Dienst\Engineering & Project Team"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Technische Dienst\Onderhoudsteam"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Logistics\Algemeen\planning\Archief"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Logistics\Algemeen\planning\Beeldscherm Koffiehok CS&L"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Logistics\Algemeen\planning\Foto's"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Logistics\Algemeen\planning\Kleding kasten"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Logistics\Algemeen\planning\Productieplanning"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Logistics\Algemeen\planning\SOP's + EPL's"
Add-HEINEKENNetworkLocation -networkLocation "\\nl2sbunfile01.nl2.heiway.net\DepartmentData\Supply Chain\Logistics\Algemeen\planning\Workloadmodel weekoverzichten"
